/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PendenteRouteImport } from './routes/pendente'
import { Route as McpRouteImport } from './routes/mcp'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedUsuariosRouteImport } from './routes/_authenticated/usuarios'
import { Route as AuthenticatedSobreRouteImport } from './routes/_authenticated/sobre'
import { Route as AuthenticatedPrestadoresRouteImport } from './routes/_authenticated/prestadores'
import { Route as AuthenticatedPrestacaoContasRouteImport } from './routes/_authenticated/prestacao-contas'
import { Route as AuthenticatedLogsAcessoRouteImport } from './routes/_authenticated/logs-acesso'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedConveniosRouteImport } from './routes/_authenticated/convenios'
import { Route as AuthenticatedConfiguracoesRouteImport } from './routes/_authenticated/configuracoes'
import { Route as AuthenticatedAuditoriaRouteImport } from './routes/_authenticated/auditoria'
import { Route as Char91DotwellKnownChar93OauthProtectedResourceRouteImport } from './routes/[.well-known]/oauth-protected-resource'
import { Route as Char91DotmcpChar93ListToolsRouteImport } from './routes/[.mcp]/list-tools'
import { Route as AuthenticatedLancamentosIndexRouteImport } from './routes/_authenticated/lancamentos.index'
import { Route as AuthenticatedLancamentosIdRouteImport } from './routes/_authenticated/lancamentos.$id'
import { Route as Char91DotmcpChar93InvokeToolToolRouteImport } from './routes/[.mcp]/invoke-tool/$tool'

const PendenteRoute = PendenteRouteImport.update({
  id: '/pendente',
  path: '/pendente',
  getParentRoute: () => rootRouteImport,
} as any)
const McpRoute = McpRouteImport.update({
  id: '/mcp',
  path: '/mcp',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedUsuariosRoute = AuthenticatedUsuariosRouteImport.update({
  id: '/usuarios',
  path: '/usuarios',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSobreRoute = AuthenticatedSobreRouteImport.update({
  id: '/sobre',
  path: '/sobre',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPrestadoresRoute =
  AuthenticatedPrestadoresRouteImport.update({
    id: '/prestadores',
    path: '/prestadores',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPrestacaoContasRoute =
  AuthenticatedPrestacaoContasRouteImport.update({
    id: '/prestacao-contas',
    path: '/prestacao-contas',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedLogsAcessoRoute = AuthenticatedLogsAcessoRouteImport.update({
  id: '/logs-acesso',
  path: '/logs-acesso',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedConveniosRoute = AuthenticatedConveniosRouteImport.update({
  id: '/convenios',
  path: '/convenios',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedConfiguracoesRoute =
  AuthenticatedConfiguracoesRouteImport.update({
    id: '/configuracoes',
    path: '/configuracoes',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAuditoriaRoute = AuthenticatedAuditoriaRouteImport.update({
  id: '/auditoria',
  path: '/auditoria',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const Char91DotwellKnownChar93OauthProtectedResourceRoute =
  Char91DotwellKnownChar93OauthProtectedResourceRouteImport.update({
    id: '/.well-known/oauth-protected-resource',
    path: '/.well-known/oauth-protected-resource',
    getParentRoute: () => rootRouteImport,
  } as any)
const Char91DotmcpChar93ListToolsRoute =
  Char91DotmcpChar93ListToolsRouteImport.update({
    id: '/.mcp/list-tools',
    path: '/.mcp/list-tools',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedLancamentosIndexRoute =
  AuthenticatedLancamentosIndexRouteImport.update({
    id: '/lancamentos/',
    path: '/lancamentos/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedLancamentosIdRoute =
  AuthenticatedLancamentosIdRouteImport.update({
    id: '/lancamentos/$id',
    path: '/lancamentos/$id',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const Char91DotmcpChar93InvokeToolToolRoute =
  Char91DotmcpChar93InvokeToolToolRouteImport.update({
    id: '/.mcp/invoke-tool/$tool',
    path: '/.mcp/invoke-tool/$tool',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/mcp': typeof McpRoute
  '/pendente': typeof PendenteRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/auditoria': typeof AuthenticatedAuditoriaRoute
  '/configuracoes': typeof AuthenticatedConfiguracoesRoute
  '/convenios': typeof AuthenticatedConveniosRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/logs-acesso': typeof AuthenticatedLogsAcessoRoute
  '/prestacao-contas': typeof AuthenticatedPrestacaoContasRoute
  '/prestadores': typeof AuthenticatedPrestadoresRoute
  '/sobre': typeof AuthenticatedSobreRoute
  '/usuarios': typeof AuthenticatedUsuariosRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/lancamentos/$id': typeof AuthenticatedLancamentosIdRoute
  '/lancamentos/': typeof AuthenticatedLancamentosIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/mcp': typeof McpRoute
  '/pendente': typeof PendenteRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/auditoria': typeof AuthenticatedAuditoriaRoute
  '/configuracoes': typeof AuthenticatedConfiguracoesRoute
  '/convenios': typeof AuthenticatedConveniosRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/logs-acesso': typeof AuthenticatedLogsAcessoRoute
  '/prestacao-contas': typeof AuthenticatedPrestacaoContasRoute
  '/prestadores': typeof AuthenticatedPrestadoresRoute
  '/sobre': typeof AuthenticatedSobreRoute
  '/usuarios': typeof AuthenticatedUsuariosRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/lancamentos/$id': typeof AuthenticatedLancamentosIdRoute
  '/lancamentos': typeof AuthenticatedLancamentosIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/mcp': typeof McpRoute
  '/pendente': typeof PendenteRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/_authenticated/auditoria': typeof AuthenticatedAuditoriaRoute
  '/_authenticated/configuracoes': typeof AuthenticatedConfiguracoesRoute
  '/_authenticated/convenios': typeof AuthenticatedConveniosRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/logs-acesso': typeof AuthenticatedLogsAcessoRoute
  '/_authenticated/prestacao-contas': typeof AuthenticatedPrestacaoContasRoute
  '/_authenticated/prestadores': typeof AuthenticatedPrestadoresRoute
  '/_authenticated/sobre': typeof AuthenticatedSobreRoute
  '/_authenticated/usuarios': typeof AuthenticatedUsuariosRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/_authenticated/lancamentos/$id': typeof AuthenticatedLancamentosIdRoute
  '/_authenticated/lancamentos/': typeof AuthenticatedLancamentosIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/mcp'
    | '/pendente'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/auditoria'
    | '/configuracoes'
    | '/convenios'
    | '/dashboard'
    | '/logs-acesso'
    | '/prestacao-contas'
    | '/prestadores'
    | '/sobre'
    | '/usuarios'
    | '/.mcp/invoke-tool/$tool'
    | '/lancamentos/$id'
    | '/lancamentos/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/mcp'
    | '/pendente'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/auditoria'
    | '/configuracoes'
    | '/convenios'
    | '/dashboard'
    | '/logs-acesso'
    | '/prestacao-contas'
    | '/prestadores'
    | '/sobre'
    | '/usuarios'
    | '/.mcp/invoke-tool/$tool'
    | '/lancamentos/$id'
    | '/lancamentos'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/mcp'
    | '/pendente'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/_authenticated/auditoria'
    | '/_authenticated/configuracoes'
    | '/_authenticated/convenios'
    | '/_authenticated/dashboard'
    | '/_authenticated/logs-acesso'
    | '/_authenticated/prestacao-contas'
    | '/_authenticated/prestadores'
    | '/_authenticated/sobre'
    | '/_authenticated/usuarios'
    | '/.mcp/invoke-tool/$tool'
    | '/_authenticated/lancamentos/$id'
    | '/_authenticated/lancamentos/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  McpRoute: typeof McpRoute
  PendenteRoute: typeof PendenteRoute
  Char91DotmcpChar93ListToolsRoute: typeof Char91DotmcpChar93ListToolsRoute
  Char91DotwellKnownChar93OauthProtectedResourceRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  Char91DotmcpChar93InvokeToolToolRoute: typeof Char91DotmcpChar93InvokeToolToolRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/pendente': {
      id: '/pendente'
      path: '/pendente'
      fullPath: '/pendente'
      preLoaderRoute: typeof PendenteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mcp': {
      id: '/mcp'
      path: '/mcp'
      fullPath: '/mcp'
      preLoaderRoute: typeof McpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/usuarios': {
      id: '/_authenticated/usuarios'
      path: '/usuarios'
      fullPath: '/usuarios'
      preLoaderRoute: typeof AuthenticatedUsuariosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/sobre': {
      id: '/_authenticated/sobre'
      path: '/sobre'
      fullPath: '/sobre'
      preLoaderRoute: typeof AuthenticatedSobreRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/prestadores': {
      id: '/_authenticated/prestadores'
      path: '/prestadores'
      fullPath: '/prestadores'
      preLoaderRoute: typeof AuthenticatedPrestadoresRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/prestacao-contas': {
      id: '/_authenticated/prestacao-contas'
      path: '/prestacao-contas'
      fullPath: '/prestacao-contas'
      preLoaderRoute: typeof AuthenticatedPrestacaoContasRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/logs-acesso': {
      id: '/_authenticated/logs-acesso'
      path: '/logs-acesso'
      fullPath: '/logs-acesso'
      preLoaderRoute: typeof AuthenticatedLogsAcessoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/convenios': {
      id: '/_authenticated/convenios'
      path: '/convenios'
      fullPath: '/convenios'
      preLoaderRoute: typeof AuthenticatedConveniosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/configuracoes': {
      id: '/_authenticated/configuracoes'
      path: '/configuracoes'
      fullPath: '/configuracoes'
      preLoaderRoute: typeof AuthenticatedConfiguracoesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/auditoria': {
      id: '/_authenticated/auditoria'
      path: '/auditoria'
      fullPath: '/auditoria'
      preLoaderRoute: typeof AuthenticatedAuditoriaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/.well-known/oauth-protected-resource': {
      id: '/.well-known/oauth-protected-resource'
      path: '/.well-known/oauth-protected-resource'
      fullPath: '/.well-known/oauth-protected-resource'
      preLoaderRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.mcp/list-tools': {
      id: '/.mcp/list-tools'
      path: '/.mcp/list-tools'
      fullPath: '/.mcp/list-tools'
      preLoaderRoute: typeof Char91DotmcpChar93ListToolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/lancamentos/': {
      id: '/_authenticated/lancamentos/'
      path: '/lancamentos'
      fullPath: '/lancamentos/'
      preLoaderRoute: typeof AuthenticatedLancamentosIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/lancamentos/$id': {
      id: '/_authenticated/lancamentos/$id'
      path: '/lancamentos/$id'
      fullPath: '/lancamentos/$id'
      preLoaderRoute: typeof AuthenticatedLancamentosIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/.mcp/invoke-tool/$tool': {
      id: '/.mcp/invoke-tool/$tool'
      path: '/.mcp/invoke-tool/$tool'
      fullPath: '/.mcp/invoke-tool/$tool'
      preLoaderRoute: typeof Char91DotmcpChar93InvokeToolToolRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAuditoriaRoute: typeof AuthenticatedAuditoriaRoute
  AuthenticatedConfiguracoesRoute: typeof AuthenticatedConfiguracoesRoute
  AuthenticatedConveniosRoute: typeof AuthenticatedConveniosRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedLogsAcessoRoute: typeof AuthenticatedLogsAcessoRoute
  AuthenticatedPrestacaoContasRoute: typeof AuthenticatedPrestacaoContasRoute
  AuthenticatedPrestadoresRoute: typeof AuthenticatedPrestadoresRoute
  AuthenticatedSobreRoute: typeof AuthenticatedSobreRoute
  AuthenticatedUsuariosRoute: typeof AuthenticatedUsuariosRoute
  AuthenticatedLancamentosIdRoute: typeof AuthenticatedLancamentosIdRoute
  AuthenticatedLancamentosIndexRoute: typeof AuthenticatedLancamentosIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAuditoriaRoute: AuthenticatedAuditoriaRoute,
  AuthenticatedConfiguracoesRoute: AuthenticatedConfiguracoesRoute,
  AuthenticatedConveniosRoute: AuthenticatedConveniosRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedLogsAcessoRoute: AuthenticatedLogsAcessoRoute,
  AuthenticatedPrestacaoContasRoute: AuthenticatedPrestacaoContasRoute,
  AuthenticatedPrestadoresRoute: AuthenticatedPrestadoresRoute,
  AuthenticatedSobreRoute: AuthenticatedSobreRoute,
  AuthenticatedUsuariosRoute: AuthenticatedUsuariosRoute,
  AuthenticatedLancamentosIdRoute: AuthenticatedLancamentosIdRoute,
  AuthenticatedLancamentosIndexRoute: AuthenticatedLancamentosIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  McpRoute: McpRoute,
  PendenteRoute: PendenteRoute,
  Char91DotmcpChar93ListToolsRoute: Char91DotmcpChar93ListToolsRoute,
  Char91DotwellKnownChar93OauthProtectedResourceRoute:
    Char91DotwellKnownChar93OauthProtectedResourceRoute,
  Char91DotmcpChar93InvokeToolToolRoute: Char91DotmcpChar93InvokeToolToolRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
